"""empty message

Revision ID: 2b0f11651423
Revises: 38f1a8e007cb
Create Date: 2024-04-30 11:09:40.461011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0f11651423'
down_revision = '38f1a8e007cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_data_po',
    sa.Column('PRODT_ORDER_NO', sa.String(), nullable=False),
    sa.Column('PLANT_CD', sa.String(), nullable=True),
    sa.Column('ITEM_CD', sa.String(), nullable=True),
    sa.Column('PLAN_START_DT', sa.Date(), nullable=True),
    sa.Column('PLAN_COMPT_DT', sa.Date(), nullable=True),
    sa.Column('ORDER_QTY_IN_BASE_UNIT', sa.Integer(), nullable=True),
    sa.Column('PROD_QTY_IN_ORDER_UNIT', sa.Integer(), nullable=True),
    sa.Column('ORDER_STATUS', sa.String(), nullable=True),
    sa.Column('RCPT_QTY_IN_ORDER_UNIT', sa.Integer(), nullable=True),
    sa.Column('RCPT_QTY_IN_BASE_UNIT', sa.Integer(), nullable=True),
    sa.Column('RCPT_FLG', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('PRODT_ORDER_NO', name=op.f('pk_import_data_po'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_permissions_permissions_name'), ['permissions_name'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_roles_rolename'), ['rolename'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_phonenumber'), ['phonenumber'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_phonenumber'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_rolename'), type_='unique')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_permissions_permissions_name'), type_='unique')

    op.drop_table('import_data_po')
    # ### end Alembic commands ###
