"""empty message

Revision ID: 38f1a8e007cb
Revises: 
Create Date: 2024-04-04 16:53:31.643922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f1a8e007cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permissions_id', sa.Integer(), nullable=False),
    sa.Column('permissions_name', sa.String(length=120), nullable=False),
    sa.Column('createdate', sa.DateTime(), nullable=True),
    sa.Column('updatedate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('permissions_id'),
    sa.UniqueConstraint('permissions_name')
    )
    op.create_table('roles',
    sa.Column('roles_id', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=120), nullable=False),
    sa.Column('createdate', sa.DateTime(), nullable=True),
    sa.Column('updatedate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('roles_id'),
    sa.UniqueConstraint('rolename')
    )
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('jobtitle', sa.String(length=120), nullable=False),
    sa.Column('phonenumber', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('createdate', sa.DateTime(), nullable=True),
    sa.Column('updatedate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('department'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('jobtitle'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phonenumber'),
    sa.UniqueConstraint('username')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('makeorder_no', sa.String(length=200), nullable=True),
    sa.Column('barcode1', sa.String(length=200), nullable=True),
    sa.Column('barcode2', sa.String(length=200), nullable=True),
    sa.Column('barcode3', sa.String(length=200), nullable=True),
    sa.Column('barcode4', sa.String(length=200), nullable=True),
    sa.Column('barcode5', sa.String(length=200), nullable=True),
    sa.Column('udi_one', sa.String(length=200), nullable=True),
    sa.Column('udi_box', sa.String(length=200), nullable=True),
    sa.Column('qr_code', sa.String(length=200), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles__permissions',
    sa.Column('roles_permissions_id', sa.Integer(), nullable=False),
    sa.Column('roles_id', sa.Integer(), nullable=False),
    sa.Column('permissions_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permissions_id'], ['permissions.permissions_id'], name='fk_roles_permissions_permissions_id', ondelete='cascade'),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.roles_id'], name='fk_roles_permissions_roles_id', ondelete='cascade'),
    sa.PrimaryKeyConstraint('roles_permissions_id')
    )
    op.create_table('users__roles',
    sa.Column('users_roles_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('roles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.roles_id'], name='fk_users_roles_roles_id', ondelete='cascade'),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], name='fk_users_roles_users_id', ondelete='cascade'),
    sa.PrimaryKeyConstraint('users_roles_id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('users__roles')
    op.drop_table('roles__permissions')
    op.drop_table('question')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
